# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Download/Install emsdk
        run: |
          git clone --depth 1 -b 5.0.1 https://github.com/emscripten-core/emsdk.git emsdk
          sudo apt-get install -y python3 git cmake xz-utils
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          
      - name: Build
        run: |
          source ./emsdk/emsdk_env.sh
          mkdir build
          cd build
          emcmake cmake ..
          emmake make -j$(nproj)

      - name: Collect build artifacts
        run: |
          mkdir public
          cp build/audio-processor.js public/
          cp build/ProjectMWasm.* public/
          cp build/index.html public/
          cp LEGAL.md public/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
